name: Push Backend Docker image

on:
  push:
    branches:
      - main
    paths:
      - 'dev/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Export .env to GitHub ENV
        run: |
          source dev/.dev.env
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Print from ENV
        run: echo "Tag is $IMAGE_TAG"

      - name: Apply kubenates resource to cluster
        run: |
          

